# Two-sample T-test

-   Compares the means of two groups
-   Three assumptions must be made:
    -   The two samples are independent of each other
    -   Each groups follows a somewhat normal distribution
    -   The two groups have similar variances

Example: comparing heights of 15 students in 2 classes
- H0: Same mean
- H1: Different means

## With scipy

In [1]:
import numpy as np

a = np.array(
    [14, 15, 15, 16, 13, 8, 14, 17, 16, 14, 19, 20, 21, 15, 15, 16, 16, 13, 14, 12]
)
a

array([14, 15, 15, 16, 13,  8, 14, 17, 16, 14, 19, 20, 21, 15, 15, 16, 16,
       13, 14, 12])

In [2]:
b = np.array(
    [15, 17, 14, 17, 14, 8, 12, 19, 19, 14, 17, 22, 24, 16, 13, 16, 13, 18, 15, 13]
)
b

array([15, 17, 14, 17, 14,  8, 12, 19, 19, 14, 17, 22, 24, 16, 13, 16, 13,
       18, 15, 13])

In [9]:
(1 / 4) < (np.var(a) / np.var(b)) < (4 / 1)
# check the variance is similar enough for the T-test

np.True_

In [15]:
import scipy.stats as stats

pvalue = stats.ttest_ind(a=a, b=b, equal_var=True).pvalue
pvalue

np.float64(0.5300471010405257)

In [17]:
pvalue > 0.05
# Cannot reject H0
# Rejects H1
# Same means

np.True_

In [18]:
a.mean()

np.float64(15.15)

In [19]:
b.mean()

np.float64(15.8)

As shown, they do have very similar means

## With pingouin

In [20]:
c = np.array(
    [160, 150, 160, 156.12, 163.24, 160.56, 168.56, 174.12, 167.123, 165.12]
)
c

array([160.   , 150.   , 160.   , 156.12 , 163.24 , 160.56 , 168.56 ,
       174.12 , 167.123, 165.12 ])

In [21]:
d = np.array(
    [157.97, 146, 140.2, 170.15, 167.34, 176.123, 162.35, 159.123, 169.43, 148.123]
)
d

array([157.97 , 146.   , 140.2  , 170.15 , 167.34 , 176.123, 162.35 ,
       159.123, 169.43 , 148.123])

In [23]:
%conda install -c conda-forge pingouin

Note: you may need to restart the kernel to use updated packages.

Solving environment: ...working... done

## Package Plan ##

  environment location: c:\Users\paul\AppData\anaconda3\envs\g4g-ds

  added / updated specs:
    - pingouin


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2025.7.9   |       h4c7d964_0         149 KB  conda-forge
    certifi-2025.7.9           |     pyhd8ed1ab_0         153 KB  conda-forge
    littleutils-0.2.4          |     pyhd8ed1ab_1          14 KB  conda-forge
    mpmath-1.3.0               |     pyhd8ed1ab_1         429 KB  conda-forge
    outdated-0.2.2             |     pyhd8ed1ab_2          13 KB  conda-forge
    pandas-flavor-0.7.0        |     pyhd8ed1ab_0          14 KB  conda-forge
    patsy-1.0.1                |     pyhd8ed1ab_1         182 KB  conda-forge
    pingouin-0.5.5             |     pyhd8ed1ab_1         162 KB  conda

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/win-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/n

In [27]:
import pingouin as pg
result = pg.ttest(c, d, correction=True)
result["p-val"] > 0.05
# Cannot reject H0
# Rejects H1
# Same means

T-test    True
Name: p-val, dtype: bool

## With statsmodels

In [24]:
%conda install -c conda-forge statsmodels

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/win-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/win-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:url

In [28]:
from statsmodels.stats.weightstats import ttest_ind

ttest_ind(c, d)[1] > 0.05
# Cannot reject H0
# Rejects H1
# Same means

np.True_