In [2]:
import numpy as np

X = np.array([0.2, 0.4, 0.6])
X

array([0.2, 0.4, 0.6])

In [3]:
y = np.array([0, 1, 1])
y

array([0, 1, 1])

In [6]:
theta = 0.5
z = X * theta
z

array([0.1, 0.2, 0.3])

In [8]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))


y_pred = sigmoid(z)
y_pred

array([0.52497919, 0.549834  , 0.57444252])

In [9]:
y_pred

array([0.52497919, 0.549834  , 0.57444252])

In [10]:
def log_loss(y_true, y_pred, eps=1e-15):
    y_pred = np.clip(y_pred, eps, 1 - eps)
    m = y_true.shape[0]
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

log_loss(y, y_pred)

np.float64(0.6322969246412299)